# Generated by Django 4.0.2 on 2022-02-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapi', '0004_alter_customer_photo_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
