# Generated by Django 4.0.2 on 2022-02-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapi', '0005_remove_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalprice',
        ),
    ]
