# Generated by Django 4.0.2 on 2022-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapi', '0006_remove_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(null=True),
        ),
    ]
